micronaut:
  application:
    name: patient-management-service
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - "http://localhost:3000"
            - "http://localhost:3001"
            - "http://localhost:4200"
            - "http://localhost:5173"
            - "http://localhost:8081"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - X-Requested-With
            - Accept
            - Origin
          exposed-headers:
            - Location
          allow-credentials: true
          max-age: 3600
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

aws:
  region: ${AWS_REGION:us-east-1}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:`http://localhost:8000`}
    table-name-prefix: ${DYNAMODB_TABLE_PREFIX:patient-mgmt-}

logger:
  levels:
    com.patientmanagement: DEBUG
    software.amazon.awssdk: DEBUG